### ISSUE TITLE
Please add a FOSS license

### ISSUE THREAD

**Issue by joachimmetz** [msuhanov/regf-samples#1]
Please consider adding a FOSS license to this project so that the test files can be reused by FOSS software under the license.

**Comment by msuhanov** [comment]
The license status of many registry hives taken from Windows installations is unclear. Such hives have signs of prepopulated data, which was manually added by someone from Microsoft (thus, these hives _can_ be considered as a work of authorship, copyrighted by Microsoft).

If you need registry hives with a FOSS license, take a look at the yarp project.

**Comment by joachimmetz** [comment]
If you are worried about authorship and copyright of these files for licensing. I opt to remove these files, since you might be re-distributing copyrighted material (without explicit consent).

**Comment by msuhanov** [comment]
> I opt to remove these files

This is the best choice if there are no applicable "fair use" or "fair use"-like rules allowing you to use these hives (and given that you decide that these hives contain copyrighted material, which isn't something obvious and indisputable, as I said before). However, the same logic can be applied to any registry hive which was originally unpacked from an installation image distributed by Microsoft (so, for example, most SYSTEM and SOFTWARE hives distributed by other projects should be considered as containing copyrighted material too).

**Comment by joachimmetz** [comment]
> and given that you decide that these hives contain copyrighted material, which isn't something obvious and indisputable, as I said before

To clarify I clearly stated a preceding if-clause namely "If you are worried about authorship and copyright of these files for licensing."

Don't put words in my mouth, so to speak. You are the one that seems to be worried about this I quote: "thus, these hives can be considered as a work of authorship, copyrighted by Microsoft"

I don't have time to argue for arguing sake. If you don't want to FOSS license it, then don't, but say so. However given your premise, I would refrain from distributing them in the first place. Since by doing so you are in violation of copyright (without explicit consent).

**Comment by msuhanov** [comment]
There is no FOSS license for these hives in order not to make "the worst case" "even worse". This is the only thing I can say about the issue, sorry if I didn't understand your second message in this thread well.
